#!/bin/bash

#####################################################
#####################################################
##      Sick of CUPS queues pausing for no reason,  #
##      Leaving your labs stuck for the night?      #
##      Me too.                                     #
##      So I wrote this little script               #
##      To cancel jobs and restart queues.          #
##                                                  #
#####################################################
#####################################################

#####  Configure these to suite your os X environment
CUPSWATCHER_PATH=/usr/local/sbin/
TIMER=30
LAUNCHD_PATH=/Library/LaunchDaemons/com.aapps.cupswatcher
CUPS_LAUNCHD="/System/Library/LaunchDaemons/org.cups.cupsd.plist"

OSKERN=`sysctl -n kern.ostype`
LOG_FILE="/var/log/cupswatcher.log"

case "$1" in

### install self and create LauchD plist file
	-i|--install)
		##### test if run as root/sudoed
		if [ `whoami` = "root" ] ; then 
			[[ ! -d "$CUPSWATCHER_PATH" ]] && mkdir -pv "$CUPSWATCHER_PATH"
			cp "$0" "$CUPSWATCHER_PATH"			

			### this next part checks if the os is OS X and installs a launchD if it is so...
				if [ "$OSKERN" == "Darwin" ]; then
					echo "Making LaunchD plist file named com.aapps.cupswatcher"
					echo "The file is located at ${LAUNCHD_PATH}"
					defaults write "$LAUNCHD_PATH" Label com.aapps.cupswatcher
					defaults write "$LAUNCHD_PATH" ProgramArguments -array "$CUPSWATCHER_PATH"cupswatcher
					defaults write "$LAUNCHD_PATH" StartInterval -int $TIMER
					chmod 644 "$LAUNCHD_PATH".plist
					[[ "$(launchctl list | grep -c cupswatcher)" = "1" ]] && launchctl unload "$LAUNCHD_PATH".plist && echo unloading old version…
					echo "Loading cupswatcher into launchD"
					launchctl load "$LAUNCHD_PATH".plist
				fi
		else
			echo the installer needs to be run as root
		exit 1
		fi	
	exit 0
	;;
	
	-r|--server)
		##### test if run as root/sudoed
		if [ `whoami` = "root" ] ; then 
			[[ ! -d "$CUPSWATCHER_PATH" ]] && mkdir -pv "$CUPSWATCHER_PATH"
			cp "$0" "$CUPSWATCHER_PATH"			

			### this next part checks if the os is OS X and installs a launchD if it is so...
				if [ "$OSKERN" == "Darwin" ]; then
					echo "Making LaunchD plist file named com.aapps.cupswatcher"
					echo "The file is located at ${LAUNCHD_PATH}"
					defaults write "$LAUNCHD_PATH" Label com.aapps.cupswatcher
					defaults write ~/Desktop/test ProgramArguments -array '("$CUPSWATCHER_PATH"cupswatcher","-s")'
					defaults write "$LAUNCHD_PATH" StartInterval -int $TIMER
					chmod 644 "$LAUNCHD_PATH".plist
					[[ "$(launchctl list | grep -c cupswatcher)" = "1" ]] && launchctl unload "$LAUNCHD_PATH".plist && echo unloading old version…
					echo "Loading cupswatcher into launchD"
					launchctl load "$LAUNCHD_PATH".plist
				fi
		else
			echo the installer needs to be run as root
		exit 1
		fi	
	exit 0
	;;

##### otherwise continue
	*)

_reload_cups(){
	launchctl unload ${CUPS_LAUNCHD}
	sleep 2
	launchctl load ${CUPS_LAUNCHD}
	exit 1
}

### run an extra routine if this is a server
if [ "$1" ==  "-s" ]; then 
	SERVER_STATUS=$(curl --silent http://127.0.0.1:631/printers/)
	RC=$?
	
	if [ $RC -gt 0 ]; then
		echo -e "The Server was restarted on $(date) due to a Print Server Crash" >> $LOG_FILE
		_reload_cups
	
	else
		PRINTER_ERROR=`echo $SERVER_STATUS | grep -c -w 'Internal Server Error'`
		if [ $PRINTER_ERROR -gt 0 ]; then 
			echo -e "The Server was restarted on $(date) due to an Printer Avaliability Error" >> $LOG_FILE
			_reload_cups
		fi
	fi
fi


#### set up varibles
ENABLE_PRINTER="$(which cupsenable)"
CANCEL_LAST_JOB="$(which lprm) -P"

[[ -z "$LOG_FILE" ]] && touch $LOG_FILE && chown root:admin $LOG_FILE && chmod 750 $LOG_FILE 

### Find any paused printers
PAUSED_PRINTER_LIST=$(lpstat -p | grep disabled | awk '{printf $2 " "}')

if [ -n "$PAUSED_PRINTER_LIST" ] ; then
	for PRINTER in ${PAUSED_PRINTER_LIST[@]} ; do 
		
#### if the same print job has stopped the queue twice, delete it (otherwise just restart the queue)  
		LAST_JOB=$(lpstat  -W not-completed | grep  $PRINTER | head -1 | awk '{print $1}')
			
			if [ -f /tmp/"$LAST_JOB" ] ; then
				$CANCEL_LAST_JOB "$PRINTER"
				$ENABLE_PRINTER "$PRINTER"
					echo "$PRINTER" was resumed and job "$LAST_JOB" was canceled on $(date) >> $LOG_FILE
						[[ -n "$LAST_JOB" ]] && rm /tmp/"$LAST_JOB"		
			else
				$ENABLE_PRINTER $PRINTER
					echo "$PRINTER" was resumed on $(date) >> $LOG_FILE
						[[ -n "$LAST_JOB" ]] && touch /tmp/"$LAST_JOB"				
			fi
	done
fi


exit 0
;;



#### end case
esac
exit 0 ;
